### ISSUE TITLE
9 Tests failing

### ISSUE THREAD

**Issue by goktugyil** [omisego/ios-sdk#18]
Maybe add Travis-CI?

**Comment by mederic-p** [comment]
Hi, thanks for trying out the SDK.
Tests are not failing if the setup is done well, please read carefully the [README](https://github.com/omisego/ios-sdk#tests) before opening an issue.
Can you post the reason of the failure here?
As stated in the README, you need to specify the different variables in order to have the live tests running correctly and I believe that you didn't do this. If you check the console you'll see "failed - Missing values for required constants. Replace them in secret.plist or pass them as environment variables.".
Regarding the CI system, we will be integrating Jenkins soon. We already have it setup for the core elixir API and will use it for our SDKs.
Lastly, there is a template for issues, please use it!

**Comment by goktugyil** [comment]
Got it, will check it out again and post the reasons if I can't make it work.

**Comment by mederic-p** [comment]
Ok, closing the issue for now.
Reopen it if you still have the same problem.
